### ISSUE TITLE
Connection close early

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/workshop-terminal#15]
With a few minutes of inactivity, it is possible that connection to the terminal is closed.

Anyway to keep terminal connection alive for at least an hour after inactivity?

**Comment by GrahamDumpleton** [comment]
If you keep the web browser open, you should not loose connectivity so long as the container running the terminal is still running. Loss of connection could technically occur where you have a dodgy network connection which keeps dropping, but if have good network, it should stay running.

In the context of using the workshop spawner, for the learning portal configuration there is a max session age (defaults 1 hour). The container for workshop will be shutdown when that time is reached and everything cleaned up. The same configuration will also shutdown and cleanup session in case where browser window on workshop was closed and there was no active connection for a period (defaults 5 minutes).

For the hosted workshop configuration, there is no max session age, and the latter idle connection timeout is set to 2 hours so that container is not shutdown even over a long lunch.

If for some reason (network issue), the terminal does show closed, refreshing the browser page should re-establish the connection and you should see what was displayed in the terminal previously and you will be back where you were. If upon refresh you aren't being returned to same point you were at, it means your workshop session was shutdown if multi user deployment, or container was restarted if standalone.

So there is no reason under normal usage with good network that the terminal connection should close and there hasn't previously been any reports of this occurring. Can you provide more details of how you are deploying the terminal? If using a standalone deployment, are you updating a custom image derived from terminal image, because doing builds of that image will update image stream for deployment and force a new deployment, which will shutdown container and close connection? That is an expected consequence of the build being linked to the deployment, but would only arise if using that when developing content.

**Comment by kaovilai** [comment]
Would it be possible to incorporate https://github.com/mobile-shell/mosh ?

I have been able to use mosh instead of ssh and it allows for multiple dropped connections while sustaining link after connection resumes.

**Comment by GrahamDumpleton** [comment]
I can't see how that would be appropriate in this case. Similar tools like screen and tmux also aren't appropriate. You should be able to refresh your browser window and get everything back because it will use the same server side terminal session state. If you aren't getting back what you had, it means your container was restarted, which those tools will not help with anyway since is a completely new instance of the application which was hosting the terminal session.

**Comment by kaovilai** [comment]
Ah true.
